### ISSUE TITLE
GNB와 Layout 구현

### ISSUE THREAD

**Issue by polycompo** [SuwonStudy/spomatch#3]
**기능 요청이 문제와 관련이 있습니까? 설명해주세요.**
GNB와 Layout을 구현합니다.

**원하는 적용 방안을 설명해주세요.**

GNB에 포함되는 기능은 아래와 같습니다.
- 왼쪽에는 햄버그 메뉴가 와야된다.
- 우측에는 사용자 정보를 표시하는 아이콘이 필요하다.
- 사용자 정보를 표시하는 아이콘은 사용자 프로필 보기와 로그아웃이 필요하다.

Layout에 포함되는 기능은 아래와 같습니다.
- 종목별 목록화면, 상세화면 등 종목에 대한 화면이 옵니다.
- 이 화면들은 route의 이동에 따라 변경될 수 있습니다.

**이와 관련된 이슈가 있습니까?**
x

**적용될때 어떠한 부수효과가 발생할 수 있습니까?**
GNB는 모든 화면에서 항상 보여야 한다.

**Comment by polycompo** [comment]
f#3-create_gnb_layout 브렌치 생성하였습니다

**Comment by seongbin9786** [comment]
closed by #15
